FROM node:22-bookworm-slim AS theme-builder

WORKDIR /build/theme
COPY wp-theme/winnica-nowizny/package.json wp-theme/winnica-nowizny/package-lock.json ./
RUN npm ci
COPY wp-theme/winnica-nowizny/ ./
RUN npm run build \
    && test -f assets/dist/.vite/manifest.json

FROM composer:2.8 AS php-dependencies

WORKDIR /build/theme
COPY wp-theme/winnica-nowizny/composer.json wp-theme/winnica-nowizny/composer.lock ./
RUN composer install \
    --no-dev \
    --no-interaction \
    --no-progress \
    --classmap-authoritative

FROM alpine:3.21 AS plugin-fetcher

RUN apk add --no-cache curl unzip \
    && mkdir -p /plugins \
    && curl -fsSL https://downloads.wordpress.org/plugin/advanced-custom-fields.6.8.6.zip -o /tmp/acf.zip \
    && unzip -q /tmp/acf.zip -d /plugins

FROM wordpress:7.0.2-php8.2-apache

COPY --from=wordpress:cli-php8.2 /usr/local/bin/wp /usr/local/bin/wp
COPY setup/apache-security.conf /etc/apache2/conf-enabled/winnica-security.conf
COPY setup/php-hardening.ini /usr/local/etc/php/conf.d/winnica-hardening.ini
COPY setup/migrate-production.sh /usr/local/bin/winnica-migrate
COPY --from=plugin-fetcher /plugins/ /usr/src/wordpress/wp-content/plugins/
COPY --from=theme-builder /build/theme/ /usr/src/wordpress/wp-content/themes/winnica-nowizny/
COPY --from=php-dependencies /build/theme/vendor/ /usr/src/wordpress/wp-content/themes/winnica-nowizny/vendor/

RUN chmod +x /usr/local/bin/winnica-migrate \
    && test -f /usr/src/wordpress/wp-content/themes/winnica-nowizny/assets/dist/.vite/manifest.json
