ServerTokens Prod
ServerSignature Off

<IfModule mod_headers.c>
    Header always unset X-Powered-By
</IfModule>

<FilesMatch "(?i)\.(log|sql|bak|old|dist)$">
    Require all denied
</FilesMatch>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>
